### ISSUE TITLE
lintのwarningを回避する&promptをVuexに書かない

### ISSUE THREAD

**Issue by m-mitsuhide** [ireversi/ireversi-client#28]
storeの「resetGame」で使っているpromptによってlintのno-alert で引っかかる。
「1行だけno-alertを無視するeslintのコメント」を挿入すること。
基本的にブラウザ依存なコードはVuexに記述しない。
DOMやwindow独自メソッドをVuexで使うとテストが非常に困難になる。

**Comment by Yohei1127** [comment]
confirmの処理をモーダルにしてもいいでしょうか？

**Comment by m-mitsuhide** [comment]
つまりpromptはVueコンポーネント側に書いて入力値だけVuexに渡す実装に変えればよい。
