### ISSUE TITLE
CirckeCIが動いてないっぽい

### ISSUE THREAD

**Issue by m-mitsuhide** [ireversi/ireversi-client#8]
木戸さんのプルリクで無反応なので調査頼みます。
https://github.com/ireversi/ireversi-client/pull/7

**Comment by hi85gh** [comment]
@m-mitsuhide @kido-k 
ご迷惑おかけして申し訳ありません。
CircleCI のチェックを手動で走らす方法が見つからず、今しばらくお待ちいただけないでしょうか。
よろしくお願いいたします。

**Comment by kido-k** [comment]
了解です。
環境構築大変とは思いますが、よろしくお願いします。
こちらの方で確認する作業があれば仰ってください。

**Comment by hi85gh** [comment]
本件、ご迷惑をおかけしております。
フォークされたリポジトリからの Pull request は CircleCI が走らないという設定ミスが見つかりました。
修正いたしましたので、次回移行は大丈夫かと思います。

**Comment by hi85gh** [comment]
@kido-k 
大変申し訳ありませんが、 CircleCI のチェックを手動で走らす方法が見つからないため、先ほど #7 でご連絡させていただいた点をご確認のうえ、再度コミット、プッシュをお願いできないでしょうか。
変更がなければこのまま強制的に手動でマージさせていただきます。

お手数をおかけいたしますがよろしくお願いいたします。

**Comment by kido-k** [comment]
再コミットで対応できることを確認しました。ありがとうございました。

**Comment by m-mitsuhide** [comment]
@hi85gh 
素晴らしい対応力！

**Comment by hi85gh** [comment]
諸々ご迷惑をおかけいたしました。
昨日動かなかった時に確認しておくべきでした。

以後、動作確認のコミット、プッシュなど注意します。
